<a href="https://colab.research.google.com/github/sonali6062/Machine_learning_fundamentals/blob/main/Gradient_Boosting(Classification).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
data=load_iris()

In [3]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
# Convert the data to a pandas DataFrame
df = pd.DataFrame(data.data, columns=data.feature_names)

# Add the target variable to the DataFrame
df['target'] = data.target

# Display the first few rows and the columns
display(df.head())
display(df.columns)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [5]:
## independent feature-x,target feature-y
x,y=data.data,data.target
print(x)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [7]:
from sklearn.ensemble import GradientBoostingClassifier
model=GradientBoostingClassifier()
model.fit(x_train,y_train)

GradientBoostingClassifier()

Perform Hyperparmeter tuning vis GridSearchCV and compare it with without tuning model

MODEL PREDICTION


In [8]:
y_pred=model.predict(x_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

MODEL EVALUATION

In [9]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy",accuracy)
print('-'*30)
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred))
print('-'*30)
print("Classification Report:")
print(classification_report(y_test,y_pred))

Accuracy 1.0
------------------------------
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
------------------------------
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



Accuracy is 1 means 100 percent. It is a clear indication that the model is overfitted(this might occur due to less record size or data leackage)

Data Modelling:GradientBoostingRegressor

In [10]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error

In [11]:
housing=fetch_california_housing()
x=housing.data
y=housing.target

Data Splitting: Split the data into independent features and target values.

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [13]:
print(y_train)

[1.03  3.821 1.726 ... 2.221 2.835 3.25 ]


Data Modelling

In [14]:
model_reg=GradientBoostingRegressor()
model_reg.fit(x_train,y_train)

GradientBoostingRegressor()

In [15]:
# Make predictions on the test set using the regression model
y_pred_reg = model_reg.predict(x_test)

y_pred_reg

array([0.50518761, 1.09334601, 4.24570956, ..., 4.68181295, 0.85329537,
       1.96275219])

In [16]:
# Evaluate the regression model using mean squared error
mse = mean_squared_error(y_test, y_pred_reg)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 0.29399732486438634


Error is very low.
lower the value of MSE higher the accuracy of the model

In [17]:
from sklearn.metrics import r2_score

# Calculate R-squared score
r2 = r2_score(y_test, y_pred_reg)
print(f"R-squared Score: {r2}")

R-squared Score: 0.7756446042829698


# Hyperparameter tuning on a Gradient Boosting Classifier

In [18]:
param_grid = {
    'n_estimators': [100, 200],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 4, 5]
}

## Initialize gridsearchcv




In [19]:
from sklearn.model_selection import GridSearchCV

grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='accuracy')

In [20]:
# Re-split the Iris data for classification
x_train_clf, x_test_clf, y_train_clf, y_test_clf = train_test_split(data.data, data.target, test_size=0.2, random_state=42)

# Fit GridSearchCV to the Iris training data
grid_search.fit(x_train_clf, y_train_clf)

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(),
             param_grid={'learning_rate': [0.01, 0.1, 0.2],
                         'max_depth': [3, 4, 5], 'n_estimators': [100, 200]},
             scoring='accuracy')

# Get best model
Extract the best performing model from the `GridSearchCV` results.


In [21]:
best_model = grid_search.best_estimator_
best_model

GradientBoostingClassifier(learning_rate=0.01)

# Make predictions
Use the best model to make predictions on the test data (x_test).


In [22]:
y_pred_tuned = best_model.predict(x_test_clf)

In [23]:
accuracy_tuned = accuracy_score(y_test_clf, y_pred_tuned)
print(f"Accuracy of the tuned model: {accuracy_tuned}")

Accuracy of the tuned model: 1.0


In [24]:
print("Best hyperparameters found:")
print(grid_search.best_params_)
print("-" * 30)
print("Accuracy of the tuned model:")
print(accuracy_tuned)

Best hyperparameters found:
{'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 100}
------------------------------
Accuracy of the tuned model:
1.0


In [25]:
# Re-split the Iris data for classification
x_train_clf, x_test_clf, y_train_clf, y_test_clf = train_test_split(data.data, data.target, test_size=0.2, random_state=42)

# Fit GridSearchCV to the Iris training data
grid_search.fit(x_train_clf, y_train_clf)

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(),
             param_grid={'learning_rate': [0.01, 0.1, 0.2],
                         'max_depth': [3, 4, 5], 'n_estimators': [100, 200]},
             scoring='accuracy')

## Get best model

Extract the best performing model from the GridSearchCV results.

In [26]:
# Extract the best performing model from the GridSearchCV results
best_model = grid_search.best_estimator_

In [27]:
# Calculate the accuracy of the predictions using accuracy_score
accuracy_tuned = accuracy_score(y_test_clf, y_pred_tuned)
print(f"Accuracy of the tuned model: {accuracy_tuned}")

Accuracy of the tuned model: 1.0


In [28]:
# Print the best hyperparameters found and the accuracy of the tuned model
print("Best hyperparameters found:")
print(grid_search.best_params_)
print("-" * 30)
print("Accuracy of the tuned model:")
print(accuracy_tuned)

Best hyperparameters found:
{'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 100}
------------------------------
Accuracy of the tuned model:
1.0


## Summary:


* The tuned model achieved perfect accuracy (1.0) on the test set, suggesting that the selected hyperparameters and model are highly effective for this specific dataset. Further validation on unseen data or with different evaluation metrics could provide additional confidence in the model's performance.
* Compare the performance of the tuned model (accuracy: 1.0) with the performance of an untuned Gradient Boosting Classifier to quantify the impact of hyperparameter tuning.