In [1]:
import numpy as np
import pandas as pd

In [2]:
data = np.array([
    [2.5, 2.4, 0.5],
    [0.5, 0.7, 1.3],
    [2.2, 2.9, 0.9],
    [1.9, 2.2, 0.7],
    [3.1, 3.0, 1.1]
])

In [3]:
dataframe=pd.DataFrame(data,columns=['x1','x2','x3'])

In [4]:
dataframe

x1   x2   x3
0  2.5  2.4  0.5
1  0.5  0.7  1.3
2  2.2  2.9  0.9
3  1.9  2.2  0.7
4  3.1  3.0  1.1

# Step1--Standard Scaler Form
To check the data is in Standard Normal form. mean=0 and standard deviation=1(we don't want our data to be biased)

In [5]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
data_standardized=scaler.fit_transform(data)
dataframe_standardized = pd.DataFrame(data_standardized, columns=dataframe.columns)

In [6]:
data_standardized

array([[ 0.53102066,  0.193687  , -1.41421356],
       [-1.77776482, -1.86423738,  1.41421356],
       [ 0.18470284,  0.79895888,  0.        ],
       [-0.16161498, -0.04842175, -0.70710678],
       [ 1.22365631,  0.92001325,  0.70710678]])

In [7]:
dataframe.describe()

x1       x2        x3
count  5.000000  5.00000  5.000000
mean   2.040000  2.24000  0.900000
std    0.968504  0.92358  0.316228
min    0.500000  0.70000  0.500000
25%    1.900000  2.20000  0.700000
50%    2.200000  2.40000  0.900000
75%    2.500000  2.90000  1.100000
max    3.100000  3.00000  1.300000

In [8]:
type(data_standardized)

numpy.ndarray

In [9]:
dataframe=pd.DataFrame(data_standardized,columns=dataframe.columns)

In [10]:
dataframe.describe()

x1            x2        x3
count  5.000000  5.000000e+00  5.000000
mean   0.000000  2.664535e-16  0.000000
std    1.118034  1.118034e+00  1.118034
min   -1.777765 -1.864237e+00 -1.414214
25%   -0.161615 -4.842175e-02 -0.707107
50%    0.184703  1.936870e-01  0.000000
75%    0.531021  7.989589e-01  0.707107
max    1.223656  9.200133e-01  1.414214

In [11]:
dataframe.shape

(5, 3)

# STEP 2- covariance matrix of given dataframe

In [12]:
 #APPROACH1
 c1=dataframe.x1
 c2=dataframe.x2
 c3=dataframe.x3

In [13]:
np.cov(dataframe)

array([[ 1.0805124 , -1.90856643,  0.23945458,  0.34700424,  0.24159521],
       [-1.90856643,  3.49074068, -0.54367187, -0.65174212, -0.38676026],
       [ 0.23945458, -0.54367187,  0.17496015,  0.11609096,  0.01316618],
       [ 0.34700424, -0.65174212,  0.11609096,  0.12404   ,  0.06460692],
       [ 0.24159521, -0.38676026,  0.01316618,  0.06460692,  0.06739195]])

In [14]:
#APPROACH2
covarianceMatrix=dataframe.T @ dataframe/4
covarianceMatrix
#@-for matrix multiplication/(n-1)

x1        x2        x3
x1  1.250000  1.174551 -0.571395
x2  1.174551  1.250000 -0.556389
x3 -0.571395 -0.556389  1.250000

In [15]:
#Approch3
np.sum(c1*c2*c3)/4

np.float64(1.3330027030554343)

# Step3- Evaluate the eigen value and eigen vector of correlation matrix

In [16]:
eigenValue,eigenVectors=np.linalg.eig(covarianceMatrix)

In [17]:
eigenValue

array([2.82765814, 0.07532468, 0.84701719])

In [18]:
eigenVectors

array([[-0.63229342, -0.70986974,  0.31030627],
       [-0.62983375,  0.70423518,  0.3276618 ],
       [ 0.4511258 , -0.01173704,  0.89238319]])

In [19]:
eigenVectors[:,0]

array([-0.63229342, -0.62983375,  0.4511258 ])

In [20]:
dataframe

x1        x2        x3
0  0.531021  0.193687 -1.414214
1 -1.777765 -1.864237  1.414214
2  0.184703  0.798959  0.000000
3 -0.161615 -0.048422 -0.707107
4  1.223656  0.920013  0.707107

In [21]:
PC1=dataframe @ eigenVectors[:,0]
PC1
#most of the features from dimentions are extracted

0   -1.095740
1    2.936217
2   -0.619998
3   -0.186308
4   -1.034171
dtype: float64

In [22]:
PC2=dataframe @ eigenVectors[:,1]
PC2

0   -0.223956
1   -0.067479
2    0.431540
3    0.088925
4   -0.229030
dtype: float64

**OBSERVATION**- Readings of PC1 is higher than PC2